// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3f5bcUspcQHFQSZ9thiljAG3-PiOJbow',
    appId: '1:736771188644:web:4afedb15f2fbcda7878331',
    messagingSenderId: '736771188644',
    projectId: 'weatherapppractice-d56b9',
    authDomain: 'weatherapppractice-d56b9.firebaseapp.com',
    storageBucket: 'weatherapppractice-d56b9.firebasestorage.app',
    measurementId: 'G-Z0CE6JRKMG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGyxMKmrMoWwugyQn_HnDxAYMSb6PIoR0',
    appId: '1:736771188644:android:47a71e4cd1bb1d21878331',
    messagingSenderId: '736771188644',
    projectId: 'weatherapppractice-d56b9',
    storageBucket: 'weatherapppractice-d56b9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCw3VMFFrg3rVy7qWPs6-4dV5qNASKHERo',
    appId: '1:736771188644:ios:f320da92f03040d8878331',
    messagingSenderId: '736771188644',
    projectId: 'weatherapppractice-d56b9',
    storageBucket: 'weatherapppractice-d56b9.firebasestorage.app',
    iosBundleId: 'com.example.weatherApp',
  );
}
