# The name of the project (required) is used for display purposes within IO environments and IDEs.
name: flutter_training

# A list of paths to local packages that are included in the Melos workspace. Each entry can be a specific path or a glob pattern.
packages:
  - apps/**
  - packages/**
  
scripts:
  postbootstrap: >
    melos exec -- puro flutter pub get

  # Clean all and remove Hanzo git hooks
  postclean: >
    melos exec -- puro flutter clean

  # Generation i18n file
  dev:generate:i18n:
    run: melos exec -- "puro flutter pub run intl_utils:generate"
    description: "Generation localizations"
    packageFilters:
      flutter: true
      scope:
        - bazar_books_app
        - bazar_books_design
       
  run:bazar_books_app:
    run: melos exec -- puro flutter run -t lib/main.dart
    packageFilters:
      scope:
        - bazar_books_app
  # Run unit test, generate html coverage and open report (MacOS support for now)
  coverage:open-report:
    run: melos exec -- flutter test --coverage && melos exec -- genhtml coverage/lcov.info -o coverage/html && melos exec -- open coverage/html/index.html
    description: Run unit testing, generate and open html coverage report.
    packageFilters:
      scope:
        - bazar_books_app

  build_runner:
    run: |
      melos exec -- "puro flutter pub run build_runner build --delete-conflicting-outputs"
    packageFilters:
      ignore:
        - app_testing
        - reply
        - shrine
        - training_form
        - training_key
        - training_layout
