name: bazar_books_design
description: "The skeleton application for Flutter with Clean Arch"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  intl: ^0.19.0
  
  talker: ^4.4.1 
  
  talker_dio_logger: ^4.4.1

    # An SVG rendering and widget library for Flutter
  flutter_svg: 2.0.9

    # BLoC for state management
  flutter_bloc: ^8.1.6

    # Sync form with BLoC
  flutter_form_bloc:
    git:
      url: https://github.com/Cavin6080/form_bloc.git
      path: packages/flutter_form_bloc

    # Navigation and routing
  go_router: 14.1.4

  smooth_page_indicator: ^1.2.0+3

  carousel_slider: ^5.0.0

  http: ^1.2.2

  shimmer: ^3.0.0

  skeletonizer: ^1.4.2

  dio: ^5.7.0

  pretty_dio_logger: ^1.4.0

  dartz: ^0.10.1
  
  form_field_validator: ^1.1.0

  isar_flutter_libs: ^3.1.0+1

  isar: ^3.1.0+1

  path_provider: ^2.1.1

  cached_query_flutter: ^2.1.0

  cached_query: ^2.0.4
  
  equatable: ^2.0.5
  
  test: ^1.25.7

  dart_style: ^2.3.7

  json: ^0.20.2

  cached_storage: ^2.0.4
  
  get_it: ^7.7.0

  permission_handler: ^11.3.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_localizations:
    sdk: flutter    

  isar_generator: ^3.1.0+1
  # Generate Dart codes library
  build_runner: ^2.4.11

  flutter_gen_runner: 5.3.2

  flutter_lints: ^3.0.0

  # intl_utils is a dart library that generates Dart localization code from ARB file. Generated code relies on Intl library.
  intl_utils: 2.8.7

  google_fonts: ^5.0.0

  flutter_rating_bar: ^4.0.1
  

dependency_overrides:
  analyzer: ^6.0.0



flutter:

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/images/

  fonts:
    - family: Roboto
      fonts:
        - asset: ../bazar_books_design/assets/fonts/Roboto-Regular.ttf
        - asset: ../bazar_books_design/assets/fonts/Roboto-Bold.ttf
        - asset: ../bazar_books_design/assets/fonts/Roboto-Medium.ttf


    - family: OpenSans
      fonts:
        - asset: ../bazar_books_design/assets/fonts/OpenSans-Regular.ttf
        - asset: ../bazar_books_design/assets/fonts/OpenSans-Bold.ttf
          weight: 700
  uses-material-design: true

# Config i18n generation
flutter_intl:
  enabled: true
  class_name: BazUiS
  arb_dir: lib/core/l10n
  output_dir: lib/core/resources/l10n_generated

# Config gen assets
flutter_gen:
  output: lib/core/resources/assets_generated/ # Optional (default: lib/gen/)
  # Optional
  integrations:
    flutter_svg: true