# This file configures the analyzer, which statically analyzes Dart code to
# check for errors, warnings, and lints.
#
# The issues identified by the analyzer are surfaced in the UI of Dart-enabled
# IDEs (https://dart.dev/tools#ides-and-editors). The analyzer can also be
# invoked from the command line by running `flutter analyze`.

include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - 'build/**'
    - '.dart_tool/**'
    - '**/*.g.dart'
    - '**/*.freezed.dart'
  errors:
    unawaited_futures: warning

linter:
  rules:
    # Style
    prefer_single_quotes: true
    always_use_package_imports: true

    # Safety
    unawaited_futures: true
    avoid_print: true
    cancel_subscriptions: true
    close_sinks: true

    # Clean code
    unnecessary_null_checks: true
    prefer_final_locals: true
    use_super_parameters: true
