part of 'light_theme.dart';

final ColorScheme _lightColorScheme = ColorScheme(
  brightness: Brightness.light,
  primary: BazColorTokens.generalPrimary[500]!,
  onPrimary: BazColorTokens.generalPrimary[50]!,
  primaryContainer: BazColorTokens.generalPurples[5],
  onPrimaryContainer: BazColorTokens.generalPurples[1],
  secondary: BazColorTokens.generalPurples[2]!,
  onSecondary: BazColorTokens.generalGreyscale[50]!,
  secondaryContainer: BazColorTokens.generalPurples[3],
  onSecondaryContainer: BazColorTokens.generalGreyscale[900],
  tertiary: BazColorTokens.generalGreyscale[500],
  onTertiary: BazColorTokens.generalGreyscale[1],
  tertiaryContainer: BazColorTokens.generalPurples[5],
  onTertiaryContainer: BazColorTokens.generalPurples[5],
  surfaceBright: BazColorTokens.generalPurples[3],
  surfaceDim: BazColorTokens.generalPurples[1],
  surfaceContainerLowest: BazColorTokens.backgroundGrey,
  surfaceContainerHighest: BazColorTokens.generalPurples[5],
  onSurfaceVariant: BazColorTokens.generalPurples[2],
  surfaceTint: BazColorTokens.generalPurples[2],
  surface: BazColorTokens.generalPrimaryRegWhite,
  onSurface: BazColorTokens.generalPurples[1]!,
  outline: BazColorTokens.generalPurples[3],
  outlineVariant: BazColorTokens.generalPurples[4],
  error: BazColorTokens.generalReds,
  onError: BazColorTokens.generalPrimaryRegWhite,
  errorContainer: BazColorTokens.generalPurples[5],
  onErrorContainer: BazColorTokens.generalPurples[1],
);
