// Mocks generated by Mockito 5.4.6 from annotations
// in todo_app/test/controllers/photo_scroll_controller_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;
import 'dart:ui' as _i4;

import 'package:flutter/material.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:todo_app/services/scroll_service.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [ScrollService].
///
/// See the documentation for Mockito's code generation for more information.
class MockScrollService extends _i1.Mock implements _i2.ScrollService {
  MockScrollService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool isNearEnd(_i3.ScrollController? controller) =>
      (super.noSuchMethod(
            Invocation.method(#isNearEnd, [controller]),
            returnValue: false,
          )
          as bool);

  @override
  double getScrollPercentage(_i3.ScrollController? controller) =>
      (super.noSuchMethod(
            Invocation.method(#getScrollPercentage, [controller]),
            returnValue: 0.0,
          )
          as double);

  @override
  bool hasSignificantScrollChange(double? oldPosition, double? newPosition) =>
      (super.noSuchMethod(
            Invocation.method(#hasSignificantScrollChange, [
              oldPosition,
              newPosition,
            ]),
            returnValue: false,
          )
          as bool);

  @override
  void addScrollListener(
    _i3.ScrollController? controller,
    _i4.VoidCallback? listener,
  ) => super.noSuchMethod(
    Invocation.method(#addScrollListener, [controller, listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeScrollListener(
    _i3.ScrollController? controller,
    _i4.VoidCallback? listener,
  ) => super.noSuchMethod(
    Invocation.method(#removeScrollListener, [controller, listener]),
    returnValueForMissingStub: null,
  );

  @override
  _i5.Future<void> scrollToTop(_i3.ScrollController? controller) =>
      (super.noSuchMethod(
            Invocation.method(#scrollToTop, [controller]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}
