// Mocks generated by Mockito 5.4.6 from annotations
// in todo_app/test/controllers/photo_detail_controller_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:ui' as _i4;

import 'package:flutter/material.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:todo_app/services/photo_animation_service.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [PhotoAnimationService].
///
/// See the documentation for Mockito's code generation for more information.
class MockPhotoAnimationService extends _i1.Mock
    implements _i2.PhotoAnimationService {
  MockPhotoAnimationService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  void initialize(_i3.TickerProvider? vsync) => super.noSuchMethod(
    Invocation.method(#initialize, [vsync]),
    returnValueForMissingStub: null,
  );

  @override
  double calculateScale(double? dragRatio) =>
      (super.noSuchMethod(
            Invocation.method(#calculateScale, [dragRatio]),
            returnValue: 0.0,
          )
          as double);

  @override
  double calculateOpacity(double? dragRatio) =>
      (super.noSuchMethod(
            Invocation.method(#calculateOpacity, [dragRatio]),
            returnValue: 0.0,
          )
          as double);

  @override
  bool shouldDismiss(
    _i4.Offset? dragOffset,
    _i3.DragEndDetails? details,
    _i4.Size? screenSize,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#shouldDismiss, [
              dragOffset,
              details,
              screenSize,
            ]),
            returnValue: false,
          )
          as bool);

  @override
  void animateToOriginalPosition(
    _i4.Offset? currentOffset,
    _i3.ValueChanged<_i4.Offset>? onUpdate,
  ) => super.noSuchMethod(
    Invocation.method(#animateToOriginalPosition, [currentOffset, onUpdate]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );
}
