name: task_management_app
description: A task management app with Pomodoro timer functionality.

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

# Flutter SDK
dependencies:
  flutter:
    sdk: flutter
  
  # UI
  cupertino_icons: ^1.0.6

  google_fonts: ^5.1.0
  
  # Routing
  go_router: ^10.1.2
  
  # Local Storage
  shared_preferences: ^2.2.1

  sqflite: ^2.3.0

  path_provider: ^2.1.1
    
  sqflite_common_ffi_web: ^0.4.5+4
  # Utilities
  uuid: ^4.0.0
  
  collection: ^1.17.2
  
  # Animation
  flutter_animate: ^4.2.0

  # Charts (for statistics)
  fl_chart: ^0.63.0

  hive: ^2.2.3

  hive_flutter: ^1.1.0

  flutter_slidable: ^4.0.0

  sqflite_common_ffi: ^2.3.4+4

  path: ^1.9.0

  provider: ^6.1.5

  device_preview: ^1.2.0

  just_audio: ^0.10.3

  just_audio_web: ^0.4.16

# Dev dependencies
dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # Linting
  flutter_lints: ^2.0.3
  
  # Testing
  mockito: ^5.4.2
  
  # Build
  build_runner: ^2.4.6
  
  # Icons
  flutter_launcher_icons: ^0.13.1
  
  # Native Splash Screen
  flutter_native_splash: ^2.3.2

# Settings Flutter
flutter:
  uses-material-design: true
