name: bazar_books_app
description: "The skeleton application for Flutter with Clean Arch"

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter
  # i18n
  intl: ^0.20.0

  # An SVG rendering and widget library for Flutter
  flutter_svg: 2.0.9

  bazar_books_design:
    path: ../bazar_books_design

  cupertino_icons: ^1.0.6

  device_preview: ^1.2.0

  flutter_native_splash: ^2.4.1

    # Responsive utilities
  responsive_framework: ^1.5.1

    # Navigation and routing
  go_router: 14.1.4

  google_fonts: ^6.2.1

  shared_preferences: ^2.3.2

  image_picker: ^1.1.2

  http: ^1.2.2

  permission_handler: ^11.3.1
 
  collection: ^1.18.0
  # Customize Flutter's default white native splash screen with background color and splash image. Supports dark mode, full screen, and more.
  flutter_bloc: ^8.1.6

  skeletonizer: ^1.4.2

  dio: ^5.7.0

  get_it: ^7.7.0

  form_field_validator: ^1.1.0

  flutter_screenutil: ^5.9.3
  
  isar_flutter_libs: ^3.1.0+1

  isar: ^3.1.0+1

  path_provider: ^2.1.1
  
  cached_query_flutter: ^2.1.0

  cached_query: ^2.0.4

  sqflite: ^2.4.0
   
  path: ^1.8.0

  bloc_concurrency: ^0.2.5

  flutter_form_builder: ^9.7.0

  equatable: ^2.0.5

  form_builder_validators: ^11.0.0

  faker: ^2.2.0

  bloc_test: ^9.1.7

  mocktail: ^1.0.4

  responsive_grid_list: ^1.4.0

  firebase_messaging: ^15.2.0

  flutter_app_badger: ^1.5.0

  firebase_core: ^3.10.0

  flutter_local_notifications: ^18.0.1

  flutter_app_badge_control: ^0.0.2

  badges: ^3.1.2

  local_auth: ^2.3.0

  app_links: ^6.3.3

  firebase_dynamic_links: ^6.1.2

  share_plus: ^10.1.4
  
  get: ^4.7.2

dev_dependencies:
  flutter_test:
    sdk: flutter
     
  # Generate Dart codes library
  build_runner: ^2.4.11

  flutter_lints: ^5.0.0

    # intl_utils is a dart library that generates Dart localization code from ARB file. Generated code relies on Intl library.
  intl_utils: ^2.8.8

dependency_overrides:
  flutter_keyboard_visibility: ^6.0.0

flutter:

  
  # To add assets to your application, add an assets section, like this:
  assets:
    - ../bazar_books_design/assets/


  fonts:
    - family: Roboto
      fonts:
        - asset: ../bazar_books_design/assets/fonts/Roboto-Regular.ttf
        - asset: ../bazar_books_design/assets/fonts/Roboto-Bold.ttf
        - asset: ../bazar_books_design/assets/fonts/Roboto-Medium.ttf


    - family: OpenSans
      fonts:
        - asset: ../bazar_books_design/assets/fonts/OpenSans-Regular.ttf
        - asset: ../bazar_books_design/assets/fonts/OpenSans-Bold.ttf
          weight: 700
  uses-material-design: true

# Config gen splash screen
flutter_native_splash:
  image: ../bazar_books_design/assets/images/splash_logo_screen.png
  color: "#54408C"

  web: false
  android_12:
    color: "#54408C"
    image: ../bazar_books_design/assets/images/splash_logo_screen.png
    image_dark: ../bazar_books_design/assets/images/splash_logo_screen.png
  enable-impeller: true

# Config i18n generation
flutter_intl:
  enabled: true
  class_name: S
  arb_dir: lib/core/l10n
  output_dir: lib/core/l10n_generated
