// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVxYmZkNeGV4ymOeVQ-tGmBoyVoJR30TM',
    appId: '1:12354716094:android:0a152d9e4b61590fd079ef',
    messagingSenderId: '12354716094',
    projectId: 'bazar-app-315a2',
    storageBucket: 'bazar-app-315a2.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0DwkhPD5_N2zuul4k8DfADMH_3pdZpUE',
    appId: '1:12354716094:web:daf38f83e9a38652d079ef',
    messagingSenderId: '12354716094',
    projectId: 'bazar-app-315a2',
    authDomain: 'bazar-app-315a2.firebaseapp.com',
    storageBucket: 'bazar-app-315a2.firebasestorage.app',
    measurementId: 'G-W3BPSMN4YQ',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1ObvCib0nEHTiqCGy-rwwjwvLjrA0iXQ',
    appId: '1:12354716094:ios:3d23a03e2a5ebe98d079ef',
    messagingSenderId: '12354716094',
    projectId: 'bazar-app-315a2',
    storageBucket: 'bazar-app-315a2.firebasestorage.app',
    iosBundleId: 'com.example.bazarBooksApp',
  );
}
