name: bazar_books_app
description: "The skeleton application for Flutter with Clean Arch"

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter
  # i18n
  intl: 0.19.0

  # An SVG rendering and widget library for Flutter
  flutter_svg: 2.0.9

  bazar_books_design:
    path: ../bazar_books_design

  cupertino_icons: ^1.0.6

  flutter_rating_bar: ^4.0.1

  device_preview: ^1.2.0

  flutter_native_splash: ^2.4.1

    # Responsive utilities
  responsive_framework: 0.2.0

    # Navigation and routing
  go_router: 14.1.4

  google_fonts: ^5.0.0

  shared_preferences: ^2.3.2

  http: ^1.2.2

  # Customize Flutter's default white native splash screen with background color and splash image. Supports dark mode, full screen, and more.
  flutter_bloc: ^8.1.6

  shimmer: ^3.0.0

  skeletonizer: ^1.4.2

  dio: ^5.7.0

  dartz: ^0.10.1

  get_it: ^7.7.0

  form_field_validator: ^1.1.0

  flutter_screenutil: ^5.9.3
  
  isar_flutter_libs: ^3.1.0+1

  isar: ^3.1.0+1

  path_provider: ^2.1.1
  
  cached_query_flutter: ^2.1.0

  cached_query: ^2.0.4

  sqflite: ^2.4.0
   
  path: ^1.8.0

  cached_storage: ^2.0.4

  bloc_concurrency: ^0.2.5

  flutter_form_builder: ^9.5.0

  equatable: ^2.0.5

  form_builder_validators: ^11.0.0

  faker: ^2.2.0

  bloc_test: ^9.1.7

  fpdart: ^1.1.0

  mocktail: ^1.0.4

  mockito: ^5.4.4


dev_dependencies:
  flutter_test:
    sdk: flutter

  # Generate Dart codes library
  build_runner: ^2.4.11

  flutter_lints: ^3.0.0

  _fe_analyzer_shared: ^72.0.0

dependency_overrides:
  # Not yet published.
  macros:
    git:
      url: https://github.com/dart-lang/sdk.git
      path: pkg/macros
      ref: main
  _fe_analyzer_shared:
    git:
      url: https://github.com/dart-lang/sdk.git
      path: pkg/_fe_analyzer_shared
      ref: main
  test_api: 0.7.0

flutter:

  
  # To add assets to your application, add an assets section, like this:
  assets:
    - ../bazar_books_design/assets/


  fonts:
    - family: Roboto
      fonts:
        - asset: ../bazar_books_design/assets/fonts/Roboto-Regular.ttf
        - asset: ../bazar_books_design/assets/fonts/Roboto-Bold.ttf
        - asset: ../bazar_books_design/assets/fonts/Roboto-Medium.ttf


    - family: OpenSans
      fonts:
        - asset: ../bazar_books_design/assets/fonts/OpenSans-Regular.ttf
        - asset: ../bazar_books_design/assets/fonts/OpenSans-Bold.ttf
          weight: 700
  uses-material-design: true

# Config gen splash screen
flutter_native_splash:
  image: ../bazar_books_design/assets/images/splash_logo_screen.png
  color: "#54408C"

  web: false
  android_12:
    color: "#54408C"
    image: ../bazar_books_design/assets/images/splash_logo_screen.png
    image_dark: ../bazar_books_design/assets/images/splash_logo_screen.png
  enable-impeller: true
